### ISSUE TITLE
display error message when user's choices are contradictory and unsupported by the edamam API

### ISSUE THREAD

**Issue by nhn39** [torieee/WSIE#101]
currently, if the user is trying to filter recipes by a wide range of diets and health labels that could be contradictory (ex: vegan  in profile but search for chicken), it leads to bad request, and the search page will remain blank. A more friendly user interface could display the error message to let users know the problem.

**Comment by Thompson632** [comment]
Added log in this PR: https://github.com/torieee/WSIE/pull/157
