### ISSUE TITLE
Check scrapers to see if that's causing Emmeline's testing issue

### ISSUE THREAD

**Issue by torieee** [torieee/WSIE#111]

**Comment by torieee** [comment]
Food52 has an issue

**Comment by emmeline2** [comment]
Debugging this error, it looks like axios can't get the link to food52. I think it is because it is requiring header or session to be initialized to access the link. Started a branch fix_scraper for this.
![image](https://github.com/torieee/WSIE/assets/24498010/95a38702-7d39-45e4-a795-369f3902f5aa)
