### ISSUE TITLE
Endpoint to clear database (not accessible via client)

### ISSUE THREAD

**Issue by nicksonsini97** [torieee/WSIE#20]
Add endpoint to clear users from database. Will be used solely to make troubleshooting and testing easier - as of now won't be accessible from website or app directly

**Comment by nicksonsini97** [comment]
endpoint added at /clearUserDatabase/

we can delete that endpoint later if we want, just figured it would help with testing since the database now lasts between images and two users can't have the same name

**Comment by torieee** [comment]
Note: this is closed but in my current branch I will push soon I added this to the top of the file so we don't have auth issues. Also added endpoint to postman team.
