### ISSUE TITLE
Wk3 - Email Verification during Signup (Multi part issue that we can break up)

### ISSUE THREAD

**Issue by torieee** [torieee/WSIE#23]
Main idea: when a new user signs up for WSIE, we want them to verify their email. This will allow us to ensure that users have valid emails. We might need to make a few yahoo or aol fake emails for testing. I've never done this (and if anyone has, please comment), but here are the things we need: 

1. mailto: {user provided email} - MailChimp
2. Authenticate: either with numbers or send user back via link in email (see notes below) - start with number for now
3. Successful signup message after authentication

NOTES: for authentication, I think it would be easiest NOW to have a randomly generated code sent in the email which the user can enter in the app. Later, when we have the app hosted, it would be easier to have a direct link back to the application. We can talk about opinions on these options.

**Comment by nicksonsini97** [comment]
I added an initial prompt and input box to appear for the confirmation code once the entries are submitted to Create Profile. I still have the verification message in place, haven't altered that yet. Code has no submission and no functionality yet.

**Comment by torieee** [comment]
One email solution (so I can find it again): https://stackoverflow.com/questions/7381150/how-to-send-an-email-from-javascript

**Comment by nicksonsini97** [comment]
I added in the random generated number as a function within endpoints, I will look into sending emails from javascript as well

**Comment by nicksonsini97** [comment]
I have the verification code parts added to both the login and new user pages in verificationCodeStructure branch - right now it just checks that the code isn't empty. Still working on utilizing the actual code from the server/sending it via email

**Comment by torieee** [comment]
<img width="682" alt="verification" src="https://github.com/torieee/WSIE/assets/86418527/0f038824-3a51-4d56-a083-231496ce8c70">
!!!!! just need to pass the verification code now

**Comment by torieee** [comment]
<img width="869" alt="verification code email" src="https://github.com/torieee/WSIE/assets/86418527/9bfd00a4-571e-4614-b6ac-c29658ef2bd2">


This is the email a new user receives
