### ISSUE TITLE
New User Input Validation

### ISSUE THREAD

**Issue by torieee** [torieee/WSIE#3]
For New Users:

Ensure username is unique (does not already exist in DB) 
Ensure valid password (ex: 8 chars, one number, etc.) 
Ensure valid email (not sure how to do this other than checking if email has @ symbol - there may be a framework)

**Comment by nicksonsini97** [comment]
Hey Torie, I can grab this one. I don't think it's letting me assign it to myself right now but I can try to get this one going!

**Comment by nicksonsini97** [comment]
So far have validation that username is only alphanumeric, that email address is valid format (checks it is string@string.string), and that password is between 5 to 15 characters and contains a number

**Comment by nicksonsini97** [comment]
I think I got the existing user check working. Updated the endpoint to check for existing username in mongoDB and then updated fetch request to handle that corresponding response

**Comment by torieee** [comment]
Great job! I assigned this one to you.

**Comment by nicksonsini97** [comment]
Validation includes:
-Email is in format string@string.string
-Username does not contain special characters
-Username is between 4-15 characters
-Password is between 8-15 characters
-Password has at least one number
-Password has at least one capital letter
-Password has at least one lowercase letter
