### ISSUE TITLE
Some recipe pages don't show the heart icon if title aligns to end of screen 

### ISSUE THREAD

**Issue by emmeline2** [torieee/WSIE#40]
Example:
![image](https://github.com/torieee/WSIE/assets/24498010/9e5d4a5e-4511-44ac-ac4e-3fd3da01c45f)

**Comment by torieee** [comment]
@emmeline2 does this happen without previously clicking favorites? Like do certain recipes just not render the heart? 

Let me know and I'll look into it

**Comment by torieee** [comment]
@emmeline2 I'll look into this
