### ISSUE TITLE
Wk 4 - Tool Tips on Heart Icon

### ISSUE THREAD

**Issue by torieee** [torieee/WSIE#53]
Add a tool tip (https://www.w3schools.com/css/css_tooltip.asp, https://www.w3schools.com/howto/howto_css_tooltip.asp) to heart icon that tells user to click/unclick to favorite/unfavorite.

**Comment by emmeline2** [comment]
Started branch: heart_icon_tooltip

**Comment by emmeline2** [comment]
Merged with this pr: https://github.com/torieee/WSIE/pull/82
