### ISSUE TITLE
Favorites Icon Status Toggling

### ISSUE THREAD

**Issue by torieee** [torieee/WSIE#6]
Currently the user can click the heart when they view a recipe to add it to their favorites list. The heart icon changes from brown to red when it is clicked. But if a user searches a recipe and clicks on one that they’ve previously favorited, the favorites icon is not red. Fix this (possibly add another attribute to the UserModel inside the “favorites”) so that previously favorited recipes’ favorites icons render red.

**Comment by emmeline2** [comment]
Merged in this pull request #39
