### ISSUE TITLE
Wk 4 - Start looking at docs for JS testing (everyone if you have time)

### ISSUE THREAD

**Issue by torieee** [torieee/WSIE#60]
Some resources (I've never done this and these look pretty basic but similar in structure to java tests).  Note that we are using Node.js specifically. If you find something you think will work, put it in the comments below. 

https://www.freecodecamp.org/news/how-to-start-unit-testing-javascript/
https://www.lambdatest.com/learning-hub/javascript-unit-testing
https://www.testim.io/blog/node-js-unit-testing-get-started-quickly-with-examples/

**Comment by nicksonsini97** [comment]
Also don't have experience with Javascript testing, but I came across Jest framework. Have some links below, going to mess with it the next few days but definitely not married to it if there's better options! It looks like the unit testing and code coverage report is pretty easy

https://jestjs.io/docs/getting-started#
https://www.youtube.com/watch?v=FgnxcUQ5vho
https://www.youtube.com/watch?v=uH5doKI8gd8

**Comment by emmeline2** [comment]
I saw Jest as a good framework as well. I tried out Jasmine just to see what it was like on branch: test_using_jasmine . 
Jasmine seems pretty similar to me, but I think you need to add another tool to get code coverage ( karma or grunt) so maybe it makes sense to go with Jest just to have everything all in one tool.

**Comment by nicksonsini97** [comment]
![Screen Shot 2024-02-04 at 9 02 13 AM](https://github.com/torieee/WSIE/assets/122702221/d208aab4-54ae-4653-8b49-c2e3ee71286d)
I haven't tried it on any server endpoints yet, and I gotta figure out how to get around the event.preventDefault() for testing some of the front end stuff but this is what it looks like from npm test. Again if we see something better that's all good too!
